In [1]:
import lands_game as lg
import lands_vars as lv
import numpy as np

In [ ]:
game = lg.LandsGame()

game.players[0]["hand"] = np.array([0, 1, 0, 0, 0])
game.players[1]["hand"] = np.array([0, 1, 0, 0, 0])
game.players[0]["deck"] = []
game.players[1]["deck"] = []
print(game.players[0]["deck"])
print(game.players[0]['discard'])
print(game.play_move([0, 1]))
print(game.play_move([1, 0]))
print(game.players[0]["deck"])
print(game.players[0]["hand"])
print(game)
print(game.play_move([0, 1]))
print(game.play_move([1, 0]))
print(game)
# print(game)
# print(game.play_move([0, 1]))
# print(game.play_move([1, 0]))
# print(game)

[]
[0. 0. 0. 0. 0.]
([[1, 0]], 0, 1)
([[0, 1]], 1, 1)
[]
[0 0 0 0 0]
board: [[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
([[1, 0]], 1, 0)
([], 0, 0)
board: [[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
