In [1]:
import os
#if you want to know current working dir
os.getcwd()
# if you want to list dir
os.listdir()

['.git',
 'env.yml',
 'envs',
 'lands_game.py',
 'lands_vars.py',
 'players.py',
 'README.md',
 'scratch_papers',
 'test_env.ipynb',
 '__pycache__']

In [2]:
import numpy as np
from gymnasium.spaces import Box, Discrete

import lands_vars as lv
import lands_game as lg
import envs.env.multi_agent_env as le

In [3]:
env = le.env()

In [4]:
env.reset()
print(env.game._get_board())

[[2 1 0 0 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [2 0 0 2 1]]


In [5]:
env.step([(5,2)])
# print(env)
print(env.game._get_board())
print(env.game.gameover)
print(env.action_space(1).sample())
# print(env.state[0])

[[2 1 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [2 0 0 3 1]]
False
[[4 1]]


c:\Users\chans\miniconda3\envs\Lands_RL\lib\site-packages\gymnasium\spaces\box.py:418: UserWarning: WARN: Casting input x to numpy array.
  gym.logger.warn("Casting input x to numpy array.")


In [6]:
lands = lg.LandsGame()

In [7]:
def generate_basic_winning_states():
  NUM_WINNING_STATES = 10
  winning_states = [{"field": np.zeros(5, dtype=np.int8), "hand": np.ones((5), dtype=np.int8), "discard": np.zeros((5), dtype=np.int8), "deck": []} for i in range(NUM_WINNING_STATES)]

  for i in range(NUM_WINNING_STATES//2):
    winning_states[i]["field"][i] = 4

  for i in range(NUM_WINNING_STATES//2, NUM_WINNING_STATES):
    winning_states[i]["field"] = np.ones(5, np.int8)
    winning_states[i]["field"][i-5] = 0

  return winning_states

In [8]:
winning_states = generate_basic_winning_states()
print(winning_states)

[{'field': array([4, 0, 0, 0, 0], dtype=int8), 'hand': array([1, 1, 1, 1, 1], dtype=int8), 'discard': array([0, 0, 0, 0, 0], dtype=int8), 'deck': []}, {'field': array([0, 4, 0, 0, 0], dtype=int8), 'hand': array([1, 1, 1, 1, 1], dtype=int8), 'discard': array([0, 0, 0, 0, 0], dtype=int8), 'deck': []}, {'field': array([0, 0, 4, 0, 0], dtype=int8), 'hand': array([1, 1, 1, 1, 1], dtype=int8), 'discard': array([0, 0, 0, 0, 0], dtype=int8), 'deck': []}, {'field': array([0, 0, 0, 4, 0], dtype=int8), 'hand': array([1, 1, 1, 1, 1], dtype=int8), 'discard': array([0, 0, 0, 0, 0], dtype=int8), 'deck': []}, {'field': array([0, 0, 0, 0, 4], dtype=int8), 'hand': array([1, 1, 1, 1, 1], dtype=int8), 'discard': array([0, 0, 0, 0, 0], dtype=int8), 'deck': []}, {'field': array([0, 1, 1, 1, 1], dtype=int8), 'hand': array([1, 1, 1, 1, 1], dtype=int8), 'discard': array([0, 0, 0, 0, 0], dtype=int8), 'deck': []}, {'field': array([1, 0, 1, 1, 1], dtype=int8), 'hand': array([1, 1, 1, 1, 1], dtype=int8), 'discard'

In [9]:
env.reset()
print(env.game._get_board())
for field in env.game.players[0]:
  env.game.players[0][field] = np.copy(winning_states[4][field])
print(env.game._get_board())

[[0 1 1 2 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 2 0 2 0]]
[[1 1 1 1 1]
 [0 0 0 0 4]
 [0 0 0 0 0]
 [1 2 0 2 0]]


In [10]:
env.step([(5,1)])
# print(env)
print(env.game._get_board())
print(env.game.gameover)
print(env.game.winner)
# print(env.state[0])

inside win
Player 1 won!
[[1 1 1 1 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [1 2 0 2 0]]
True
0


In [16]:
print(env.agent_iter())
for agent in env.agent_iter():
  observation, reward, termination, truncation, info = env.last()

  if termination or truncation:
    action = None
  env.step(action)
  print(agent)

player_1
player_0


In [11]:
# TODO test whether basic StableBaseline learn from the env
